finance_app/account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path('', AllAccountView.as_view(), name='accounts'),
    path('operations/<int:time>/', AllOperationsView.as_view(), name='operations'),
    path('operations/<int:pk>/<int:time>/', OperationsOneAccountView.as_view(), name='operationsOne'),
    path('new/', CreateNewAccountView.as_view(), name='CreateAccount'),
    path('newoperation/', CreateOperationView.as_view(), name='CreateOperation'),
    path('newlimit/', CreateNewLimitView.as_view(), name='CreateLimit'),
    path('limit/', LimitView.as_view(), name='Limit'),
    path('operation/<int:pk>', DeleteOperationView.as_view(), name='DeleteOperation'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

finance_app/finance_app/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from account.apiviews import *

# router = routers.DefaultRouter()
# router.register(r'accounts', AccountsViewSet)
# router.register(r'operations', OperationsViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls', namespace='users')),
    path('', include('account.urls', namespace='Accounts')),
    path('api/v1/token', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh', TokenRefreshView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/verify', TokenVerifyView.as_view(), name='token_obtain_pair'),
    path('api/v1/accounts/', AccountsAPIList.as_view()),
    path('api/v1/operations/<int:pk>', OperationsAPIList.as_view()),
]

finance_app/users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('registration/', RegistrationUserView.as_view(), name='registration'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('exit/', logout, name='exit'),
]

finance_app/users/models.py
from django.db import models

# Create your models here.

finance_app/users/forms.py
from django import forms


class UserForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())


class LoginUserForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

finance_app/users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.models import User
from django.urls import reverse
from django.views import View
from .forms import UserForm, LoginUserForm
from django.contrib import auth


class RegistrationUserView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "users/registration.html", {'form': UserForm()})

    def post(self, request, *args, **kwargs):
        form = UserForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            User.objects.create_user(username=username, password=password)
            return render(request, "users/registration.html", {'form': form})

        HttpResponseRedirect(reverse('users:login'))


class LoginUserView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/login.html', {'form': LoginUserForm()})

    def post(self, request, *args, **kwargs):
        form = LoginUserForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
        else:
            form = LoginUserForm()
        context = {"form": form}
        return HttpResponseRedirect(reverse('Accounts:accounts'))


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('Accounts:profile'))

finance_app/users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link href="{% static 'users/base.css' %}" rel="stylesheet"/>
    {% block style %} {% endblock %}
</head>
<body>
    <div class="head">
        <a class="button" href="{% url 'Accounts:accounts' %}">My Accounts</a>
        <a class="button" href="{% url 'users:login' %}">Authorization</a>
        <a class="button" href="{% url 'users:registration' %}">Registration</a>
    </div>
    <div>
        {% block content %} {% endblock %}
    </div>
</body>
</html>

finance_app/users/templates/users/login.html
{% extends 'users/base.html' %}
{% block style %}
  {% load static %}
  <link href="{% static 'users/login.css' %}" rel="stylesheet"/>
{% endblock %}
{% block content %}
  <h1 class="field">Authorization</h1>
  <form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div class="field">
      <p>Login</p>
      {{ form.username }}
    </div>
    <div class="field">
      <p>Password</p>
      {{ form.password }}
    </div>
    <div class="field">
      <input type="submit" value="Login">
    </div>
  </form>
{% endblock %}

finance_app/users/templates/users/registration.html
{% extends 'users/base.html' %}
{% block style %}
  {% load static %}
  <link href="{% static 'users/registration.css' %}" rel="stylesheet"/>
{% endblock %}
{% block content %}
  <h1 class="field">Registration</h1>
  <form action="{% url 'users:registration' %}" method="post">
    {% csrf_token %}
    <div class="field">
      <p>Login</p>
      {{ form.username }}
    </div>
    <div class="field">
      <p>Password</p>
      {{ form.password }}
    </div>
    <div class="field">
      <input type="submit" value="Registration">
    </div>
  </form>
{% endblock %}